### PR TITLE
Key logging changes

### PR DESCRIPTION
**Pull request by gamester543**
Changed storage of keys to boolean values
Simplified getKeysPressed

### CODE REVIEW

**Comment by finnbear** [comment]
This is actually needed
var key = arr[i]
keys[e.keyCode] = e.keyCode;
The key codes are right, unless they are not working for you. They correspond to Arrow Keys and WASD keys.

**Comment by gamester543** [comment]
The index of the keycode will be e.keyCode

keys[e.keyCode] sets the value at index "e.keycode" to e.keyCode which is unneeded.

**Comment by finnbear** [comment]
Your right, there is a problem, but I think the solution would be to make the index 0-Infinity and the data stored be the keycode, not the other way around.

_In other words..._
**In-efficient & Bad:** `keys[e.keyCode] = e.keyCode;`
**Efficient & Bad** `keys[e.keyCode] = true`
**Efficient & Good** `keys[i] = e.keyCode`
That way, when you want to iterate through the list, you dont have to check if the item at the index is `null`, `NaN`, or invalid.

Your way does work, and if you would like, I will implement it.

**Comment by gamester543** [comment]
Thanks. The problem with having _keys[i] = e.keycode_ is that removing a key from the list requires searching the list and removing all instances of e.keycode, and then shifting the list over.

Adding elements would need a check to keys[keys.length - 1] to rid of duplicates.

**Comment by finnbear** [comment]
Fair enough.

Btw, the key codes don't seem right because they don't correspond to the characters that are posted to our server. For exapmle
`w or <up arrow>` gets changed to `"U"`

**Pull request merged**
